title: Malavika Vasist
description: My professional website
remote_theme: pages-themes/jekyll-theme-slate
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

url: "https://malavikavasist.github.io"
baseurl: ""

